/motion_capture_tracking:
  ros__parameters:
    # one of "optitrack", "optitrack_closed_source", "vicon", "qualisys", "nokov", "vrpn", "motionanalysis"
    type: "optitrack" #"qualisys"
    # Specify the hostname or IP of the computer running the motion capture software
    hostname: "10.0.0.96"

    topics:
      frame_id: "mocap"
      poses:
        qos:
          mode: "sensor"
          deadline: 100.0 # Hz
      tf:
        child_frame_id: "{}_mocap"

    marker_configurations:
      default: # for standard Crazyflie
        offset: [0.0, 0.0, 0.0]
        points:
          p0: [   0.0,    0.0, 0.022]  # top
          p1: [-0.042,  0.042, 0.0  ]  # back left   (M3)
          p2: [-0.042, -0.042, 0.0  ]  # back right  (M2)
          p3: [ 0.042, -0.042, 0.0  ]  # front right (M1)
      my_arrangement:
        offset: [0.0, 0.0, 0.0]
        points:
          p0: [   0.0,    0.0, 0.022]  # top
          p1: [ 0.042,  0.042, 0.0  ]  # back left   (M3)
          p2: [ 0.042, -0.042, 0.0  ]  # front right (M1)
      my_new_arrangement:
        offset: [0.0, 0.0, 0.0]
        points:
          # p0: [   0.0,      0.0, 0.022]  # top
          # p1: [ 63.085,  44.515, 10.632]  # front left
          # p2: [ 63.085, -44.515, 10.632]  # front right
          # p3: [-51.085,  44.515, 10.632]  # back left
          # p0: [      0.0,      0.0,  0.012]  # top
          # p1: [ 0.063085,  0.044515, 0.019]  # front left
          # p2: [ 0.063085, -0.044515, 0.019]  # front right
          # p3: [-0.051085,  0.044515, 0.019]  # back left
          # p0: [      0.0,      0.0,  0.012]  # top
          # p1: [ 0.060085,  0.044515, 0.019]  # front left
          # p2: [ 0.060085, -0.044515, 0.019]  # front right
          # p3: [-0.053085,  0.044515, 0.019]  # back left
          p1: [-0.0523, 0.0454,  0.0200]
          p2: [ 0.0594, 0.0441,  0.0192]
          p3: [-0.0010, 0.0003,  0.0108]
          p4: [ 0.0601, -0.0425, 0.0175]
          # p4: [-51.085, -44.515, 7.632]  # back right
          # p4: [-51.085, -44.515, 7.632]  # back right
      arrangement_smarc:
        offset: [0.0, 0.0, 0.0]
        points:
          p0: [-0.03,  0.0, 0.0]
          p1: [ 0.03, 0.0, 0.0]
          p2: [ 0.0,  -0.03, 0.0]
      
      arrangement_v2:
        offset: [0.0, 0.0, 0.0]
        points:
          p0: [-0.03350,  0.04078, -0.01345]
          p1: [ 0.04996, -0.04180, -0.01345]
          p2: [ 0.04952,  0.04078, -0.01345]
          p3: [ 0.01200,  0.00000,  0.00800]
      arrangement_v3:
        offset: [0.0, 0.0, 0.0]
        points:
          p0: [ 0.000, 0.000, 0.006]
          p1: [ 0.017,-0.028,-0.008]
          p2: [-0.009, 0.025,-0.014]
          # p0: [ 0.022,-0.030,-0.010]
          # p0: [-0.010, 0.027,-0.009]
      default_single_marker:
        offset: [0.0, -0.01, -0.04]
        points:
          p0: [0.0177184,0.0139654,0.0557585]
      mocap_deck:
        offset: [0.0, 0.0, -0.01]
        points:
          p0: [0.03, 0.0, 0.0] # front
          p1: [0.00, -0.03, 0.0] # right
          p2: [-0.015, 0.0, 0.0] # back
          p3: [0.00, 0.03, 0.0] # left
      medium_frame:
        offset: [0.0, 0.0, -0.03]
        points:
          p0: [-0.00896228,-0.000716753,0.0716129]
          p1: [-0.0156318,0.0997402,0.0508162]
          p2: [0.0461693,-0.0881012,0.0380672]
          p3: [-0.0789959,-0.0269793,0.0461144]
      big_frame:
        offset: [0.0, 0.0, -0.06]
        points:
          p0: [0.0558163,-0.00196302,0.0945539]
          p1: [-0.0113941,0.00945842,0.0984811]
          p2: [-0.0306277,0.0514879,0.0520456]
          p3: [0.0535816,-0.0400775,0.0432799]

    dynamics_configurations:
      default:
        max_velocity: [2, 2, 3] # m/s
        max_angular_velocity: [20, 20, 10] # rad/s
        max_roll: 1.4 #rad
        max_pitch: 1.4 #rad
        max_fitness_score: 0.001

    # Rigid bodies will be automatically generated by the launch file
    # rigid_bodies:
